export type DifficultyLevel = "Easy" | "Medium" | "Hard";

export interface DataStructureInfo {
  id: string;
  name: string;
  slug: string;
  difficulty: DifficultyLevel;
  tagline: string;
  description: string;
  visualType: "array" | "linked-list" | "stack" | "queue" | "hash-table" | "tree" | "heap" | "graph" | "trie";
  accessTime: string;
  searchTime: string;
  insertTime: string;
  deleteTime: string;
}

export const DATA_STRUCTURES_CATALOG: DataStructureInfo[] = [
  {
    id: "arrays",
    name: "Arrays",
    slug: "arrays",
    difficulty: "Easy",
    tagline: "Contiguous memory sequence",
    description: "Store elements in contiguous positions and access them using direct zero-based indexes.",
    visualType: "array",
    accessTime: "O(1)",
    searchTime: "O(n)",
    insertTime: "O(n)",
    deleteTime: "O(n)",
  },
  {
    id: "linked-lists",
    name: "Linked Lists",
    slug: "linked-lists",
    difficulty: "Easy",
    tagline: "Chained pointer nodes",
    description: "Sequence of nodes where each node contains data and a reference to the next node.",
    visualType: "linked-list",
    accessTime: "O(n)",
    searchTime: "O(n)",
    insertTime: "O(1)",
    deleteTime: "O(1)",
  },
  {
    id: "stacks",
    name: "Stacks",
    slug: "stack",
    difficulty: "Easy",
    tagline: "Last-In First-Out (LIFO)",
    description: "Linear container with push and pop operations confined to the top element.",
    visualType: "stack",
    accessTime: "O(n)",
    searchTime: "O(n)",
    insertTime: "O(1)",
    deleteTime: "O(1)",
  },
  {
    id: "queues",
    name: "Queues",
    slug: "queue",
    difficulty: "Easy",
    tagline: "First-In First-Out (FIFO)",
    description: "Ordered container where elements insert at the rear and depart from the front.",
    visualType: "queue",
    accessTime: "O(n)",
    searchTime: "O(n)",
    insertTime: "O(1)",
    deleteTime: "O(1)",
  },
  {
    id: "hash-tables",
    name: "Hash Tables",
    slug: "hash-table",
    difficulty: "Medium",
    tagline: "Key-value hash mapping",
    description: "Associates keys to memory buckets via hashing functions for near-instant lookups.",
    visualType: "hash-table",
    accessTime: "O(1) Avg",
    searchTime: "O(1) Avg",
    insertTime: "O(1) Avg",
    deleteTime: "O(1) Avg",
  },
  {
    id: "trees",
    name: "Trees",
    slug: "trees",
    difficulty: "Medium",
    tagline: "Hierarchical parent-child nodes",
    description: "Hierarchical structure with a root node branched into left and right subtrees.",
    visualType: "tree",
    accessTime: "O(log n)",
    searchTime: "O(log n)",
    insertTime: "O(log n)",
    deleteTime: "O(log n)",
  },
  {
    id: "binary-tree",
    name: "Binary Tree",
    slug: "binary-tree",
    difficulty: "Medium",
    tagline: "Hierarchical two-child node structure",
    description: "Hierarchical data structure where each parent node has at most two children: left and right.",
    visualType: "tree",
    accessTime: "O(n)",
    searchTime: "O(n)",
    insertTime: "O(1)",
    deleteTime: "O(1)",
  },
  {
    id: "bst",
    name: "Binary Search Tree (BST)",
    slug: "bst",
    difficulty: "Medium",
    tagline: "Ordered binary tree for rapid search",
    description: "Binary tree maintaining the key invariant: left subtree < node < right subtree for logarithmic lookups.",
    visualType: "tree",
    accessTime: "O(log n)",
    searchTime: "O(log n)",
    insertTime: "O(log n)",
    deleteTime: "O(log n)",
  },
  {
    id: "heaps",
    name: "Heaps",
    slug: "heap",
    difficulty: "Medium",
    tagline: "Priority-ordered binary tree",
    description: "Specialized complete binary tree satisfying the min-heap or max-heap property.",
    visualType: "heap",
    accessTime: "O(1) Peek",
    searchTime: "O(n)",
    insertTime: "O(log n)",
    deleteTime: "O(log n)",
  },
  {
    id: "priority-queue",
    name: "Priority Queue",
    slug: "priority-queue",
    difficulty: "Medium",
    tagline: "Heap-backed dynamic task scheduler",
    description: "Abstract queue data type where elements have priorities and higher priority tasks are dequeued first.",
    visualType: "heap",
    accessTime: "O(1) Peek",
    searchTime: "O(n)",
    insertTime: "O(log n)",
    deleteTime: "O(log n)",
  },
  {
    id: "graphs",
    name: "Graphs",
    slug: "graphs",
    difficulty: "Hard",
    tagline: "Network of vertices and edges",
    description: "A graph is a collection of vertices connected by edges.",
    visualType: "graph",
    accessTime: "O(V + E)",
    searchTime: "O(V + E)",
    insertTime: "O(1)",
    deleteTime: "O(E)",
  },
  {
    id: "tries",
    name: "Tries",
    slug: "trie",
    difficulty: "Hard",
    tagline: "Prefix tree for strings",
    description: "Tree structure optimized for rapid retrieval of string prefixes and autocompletion.",
    visualType: "trie",
    accessTime: "O(k)",
    searchTime: "O(k)",
    insertTime: "O(k)",
    deleteTime: "O(k)",
  },
];

export interface AlgorithmInfo {
  id: string;
  name: string;
  slug: string;
  category: "Searching" | "Sorting" | "Graphs" | "Recursion" | "Dynamic Programming" | "Greedy" | "Backtracking";
  difficulty: DifficultyLevel;
  description: string;
  timeComplexity: string;
  spaceComplexity: string;
}

export const ALGORITHMS_CATALOG: AlgorithmInfo[] = [
  {
    id: "linear-search",
    name: "Linear Search",
    slug: "linear-search",
    category: "Searching",
    difficulty: "Easy",
    description: "Sequentially checks each element in the list until a match is found or the end is reached.",
    timeComplexity: "O(n)",
    spaceComplexity: "O(1)",
  },
  {
    id: "binary-search",
    name: "Binary Search",
    slug: "binary-search",
    category: "Searching",
    difficulty: "Easy",
    description: "Find an element efficiently in a sorted collection by halving search boundaries.",
    timeComplexity: "O(log n)",
    spaceComplexity: "O(1)",
  },
  {
    id: "bubble-sort",
    name: "Bubble Sort",
    slug: "bubble-sort",
    category: "Sorting",
    difficulty: "Easy",
    description: "Repeatedly steps through the list, compares adjacent items, and swaps misplaced pairs.",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
  },
  {
    id: "selection-sort",
    name: "Selection Sort",
    slug: "selection-sort",
    category: "Sorting",
    difficulty: "Easy",
    description: "Selects the minimal element from the unsorted segment and moves it to the beginning.",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
  },
  {
    id: "insertion-sort",
    name: "Insertion Sort",
    slug: "insertion-sort",
    category: "Sorting",
    difficulty: "Easy",
    description: "Builds sorted output by inserting one element at a time into its proper position.",
    timeComplexity: "O(n²)",
    spaceComplexity: "O(1)",
  },
  {
    id: "merge-sort",
    name: "Merge Sort",
    slug: "merge-sort",
    category: "Sorting",
    difficulty: "Medium",
    description: "Divide-and-conquer sorting algorithm that splits the array and merges sorted halves.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(n)",
  },
  {
    id: "quick-sort",
    name: "Quick Sort",
    slug: "quick-sort",
    category: "Sorting",
    difficulty: "Medium",
    description: "Selects a pivot element to partition the array into smaller and greater elements.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(log n)",
  },
  {
    id: "bfs",
    name: "Breadth-First Search (BFS)",
    slug: "bfs",
    category: "Graphs",
    difficulty: "Medium",
    description: "Explores all neighboring vertices level-by-level using an auxiliary queue.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
  },
  {
    id: "dfs",
    name: "Depth-First Search (DFS)",
    slug: "dfs",
    category: "Graphs",
    difficulty: "Medium",
    description: "Explores as deep as possible along each branch before backtracking via stack or recursion.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
  },
  {
    id: "dijkstra",
    name: "Dijkstra's Algorithm",
    slug: "dijkstra",
    category: "Graphs",
    difficulty: "Hard",
    description: "Calculates the shortest paths from a single source node in non-negative weighted graphs.",
    timeComplexity: "O((V + E) log V)",
    spaceComplexity: "O(V)",
  },
  {
    id: "bellman-ford",
    name: "Bellman-Ford Algorithm",
    slug: "bellman-ford",
    category: "Graphs",
    difficulty: "Hard",
    description: "Computes single-source shortest paths while detecting negative-weight cycles.",
    timeComplexity: "O(V · E)",
    spaceComplexity: "O(V)",
  },
  {
    id: "prim",
    name: "Prim's Algorithm (MST)",
    slug: "prim",
    category: "Graphs",
    difficulty: "Medium",
    description: "Greedy algorithm that finds a Minimum Spanning Tree for a connected weighted undirected graph.",
    timeComplexity: "O((V + E) log V)",
    spaceComplexity: "O(V)",
  },
  {
    id: "kruskal",
    name: "Kruskal's Algorithm (MST)",
    slug: "kruskal",
    category: "Graphs",
    difficulty: "Medium",
    description: "Finds a Minimum Spanning Tree using Union-Find by greedily selecting the lowest-weight edges.",
    timeComplexity: "O(E log E)",
    spaceComplexity: "O(V)",
  },
  {
    id: "topological-sort",
    name: "Topological Sort (Kahn's)",
    slug: "topological-sort",
    category: "Graphs",
    difficulty: "Medium",
    description: "Linear ordering of vertices in a DAG such that for every directed edge u -> v, u comes before v.",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
  },
  {
    id: "recursion",
    name: "Recursion & Trees",
    slug: "recursion",
    category: "Recursion",
    difficulty: "Medium",
    description: "Solves problems by decomposing them into identical subproblems with base stopping cases.",
    timeComplexity: "O(2ⁿ) or O(n)",
    spaceComplexity: "O(d) stack",
  },
  {
    id: "dp",
    name: "Dynamic Programming",
    slug: "dp",
    category: "Dynamic Programming",
    difficulty: "Hard",
    description: "Stores overlapping subproblem solutions to prevent redundant recalculation.",
    timeComplexity: "O(n · W)",
    spaceComplexity: "O(n)",
  },
  {
    id: "greedy",
    name: "Greedy Strategies",
    slug: "greedy",
    category: "Greedy",
    difficulty: "Medium",
    description: "Makes the locally optimal choice at each stage in hopes of finding a global optimum.",
    timeComplexity: "O(n log n)",
    spaceComplexity: "O(1)",
  },
  {
    id: "backtracking",
    name: "Backtracking (N-Queens)",
    slug: "backtracking",
    category: "Backtracking",
    difficulty: "Hard",
    description: "Systematically searches all candidate solutions and discards partial candidates early.",
    timeComplexity: "O(N!)",
    spaceComplexity: "O(N)",
  },
];

export interface RoadmapStep {
  stepNumber: number;
  title: string;
  description: string;
  tag: string;
  href: string;
}

export const LEARNING_ROADMAP: RoadmapStep[] = [
  { stepNumber: 1, title: "Programming Basics", description: "Variables, loops, arrays, and memory references.", tag: "Fundamentals", href: "/learn" },
  { stepNumber: 2, title: "Arrays", description: "Indexing, traversal, contiguous storage, and bounds.", tag: "Data Structure", href: "/data-structures#arrays" },
  { stepNumber: 3, title: "Linked Lists", description: "Node chaining, pointers, head/tail mutations.", tag: "Data Structure", href: "/data-structures#linked-lists" },
  { stepNumber: 4, title: "Stacks & Queues", description: "LIFO call stacks and FIFO buffering mechanisms.", tag: "Data Structure", href: "/data-structures#stack" },
  { stepNumber: 5, title: "Hash Tables", description: "Key hashing, collision handling, and constant time lookups.", tag: "Data Structure", href: "/data-structures#hash-table" },
  { stepNumber: 6, title: "Trees", description: "Hierarchical trees, BST search invariants, and traversals.", tag: "Data Structure", href: "/data-structures#trees" },
  { stepNumber: 7, title: "Graphs", description: "Adjacency lists, matrices, BFS, DFS, and paths.", tag: "Data Structure", href: "/data-structures#graphs" },
  { stepNumber: 8, title: "Algorithms", description: "Binary search, merge sort, quick sort, and BFS/DFS.", tag: "Algorithms", href: "/algorithms" },
  { stepNumber: 9, title: "Advanced DSA", description: "Dynamic programming, shortest paths, and backtracking.", tag: "Advanced", href: "/algorithms" },
];

export const FEATURE_CARDS_DATA = [
  {
    id: "visual-learning",
    title: "Visual Learning",
    description: "See algorithms execute step by step instead of guessing what code is doing in memory.",
    iconName: "Eye",
  },
  {
    id: "code-sync",
    title: "Code Synchronization",
    description: "Follow the exact code lines and inspect variables live as the algorithm runs.",
    iconName: "Code2",
  },
  {
    id: "interactive-practice",
    title: "Interactive Practice",
    description: "Experiment with your own inputs and predict what happens next at critical steps.",
    iconName: "Sliders",
  },
  {
    id: "step-execution",
    title: "Step-by-Step Execution",
    description: "Pause, step forward, step backward, or jump across the execution timeline freely.",
    iconName: "PlaySquare",
  },
  {
    id: "multiple-languages",
    title: "Multiple Languages",
    description: "Learn concepts with Python, C++, Java, and TypeScript implementations.",
    iconName: "Languages",
  },
  {
    id: "progress-tracking",
    title: "Progress Tracking",
    description: "Track your topic mastery, practice streaks, and completed problem milestones.",
    iconName: "Trophy",
  },
];
